//HintName: TestVM.ObservableAsPropertyFromObservable.g.cs
// <auto-generated/>
using ReactiveUI;

#nullable enable

namespace TestNs
{
    /// <summary>
    /// Partial class for the TestVM which contains ReactiveUI ObservableAsPropertyHelper initialization.
    /// </summary>
    public partial class TestVM
    {
        /// <summary>
        /// The observable property for .
        /// </summary>
        
        private global::System.IObservable<int> _test2;

        /// <summary>
        /// The observable property helper for .
        /// </summary>
        private ReactiveUI.ObservableAsPropertyHelper<global::System.IObservable<int>>? _test2Helper;

        /// <summary>
        /// Gets the  property.
        /// </summary>
        
        public global::System.IObservable<int>  =>
            _test2Helper?.Value ?? _test2;

        /// <summary>
        /// Initializes all observable properties.
        /// </summary>
        protected void InitializeOAPH()
        {
            _test2Helper = Test2()!.ToProperty(this, nameof());
        }
    }
}